name: CI
on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            bin_path: Cpp2IL/Linux
            # Not working
          # - os: ubuntu-latest
            # arch: arm64
            # bin_path: Cpp2IL/Linux-arm64
          - os: macos-latest
            arch: x64
            bin_path: Cpp2IL/macOS
          - os: macos-latest
            arch: arm64
            bin_path: Cpp2IL/macOS-arm64
          - os: windows-latest
            arch: x64
            bin_path: Cpp2IL/Windows

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.arch }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Test Cpp2IL binary
        run: |
          cd "${{ matrix.bin_path }}"
          chmod +x Cpp2IL 2>/dev/null || true
          ./Cpp2IL --version
        shell: bash

      - name: Install pip modules
        run: |
          pip install dearpygui httpx pyinstaller

      - name: Compile project
        run: |
          pyinstaller --onefile main.py

      - name: Create zip archive
        run: |
            if [ "${{ runner.os }}" = "Windows" ]; then
            cp "${{ matrix.bin_path }}/Cpp2IL.exe" "Assets/Cpp2IL.exe"
            cp "dist/main.exe" "main.exe"
            else
            cp "${{ matrix.bin_path }}/Cpp2IL" "Assets/Cpp2IL"
            cp "dist/main" "main"
            fi
    
            zip -r build.zip Assets main.exe
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.arch }}
          path: build.zip
