name: CI
on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.arch }}
    
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Testing Cpp2IL on Ubuntu x86_64
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd Cpp2IL/Linux
          chmod 777 Cpp2IL
          ./Cpp2IL --version
        
      - name: Testing Cpp2IL on Ubuntu arm64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: |
          cd Cpp2IL/Linux
          chmod 777 Cpp2IL
          ./Cpp2ILarm64 --version

      - name: Testing Cpp2IL on macOS x86_64
        if: matrix.os == 'macos-latest'
        run: |
          cd Cpp2IL/macOS
          chmod 777 Cpp2IL
          ./Cpp2IL --version
        
      - name: Testing Cpp2IL on macOS arm64
        if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
        run: |
          cd Cpp2IL/macOS
          chmod 777 Cpp2IL
          ./Cpp2ILarm64 --version
        
      - name: Testing Cpp2IL on Windows x86_64
        if: matrix.os == 'windows-latest'
        run: |
          cd Cpp2IL/Windows
          ./Cpp2IL --version

   